import type { NextPage } from 'next';
import Head from 'next/head';

import styles from 'styles/Home.module.css';

// test
import React, { useState, useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { login } from '../redux/actions/loginAction';
import {RootState} from "../redux/rootReducer";

const Home: NextPage = () => {

  const [ state, setState ] = useState({
    userName: ''
  });

  const common = useSelector((state: RootState) => state.common);
  const auth = useSelector((state: RootState) => state.auth);
  const dispatch = useDispatch();

  const handleLogin = (userName: string) => {
    dispatch(login(userName));
  };

  const handleChange = (e: any) => {
    setState({
      userName: e.target.value
    })
  }

  useEffect(() => {

  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Github user 조회 테스트
        <input
          type="text"
          name="userName"
          onChange={(e) => handleChange(e)}
        />
        <button type="button" onClick={() => handleLogin(state.userName)}>로그인</button>

        <p>{common.isLoading && '로딩중'}</p>

        <div>
          <ul>
            <li>name: {auth.data?.name ? auth.data.name : '미설정 or 조회 실패'}</li>
          </ul>
        </div>
      </main>
    </div>
  );
};

export default Home;
